# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171229_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
