# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180115_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationgrant',
            name='invitation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='api.Invitation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='selling_mode',
            field=models.CharField(choices=[('P', "Public (en fonction de l'évènement)"), ('I', 'Sur invitation direct'), ('L', 'Verrouillé')], default='P', max_length=1, verbose_name='mode de vente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_mode',
            field=models.CharField(choices=[('P', "Public (en fonction de l'évènement)"), ('I', 'Sur invitation direct'), ('L', 'Verrouillé')], default='P', max_length=1, verbose_name='mode de vente'),
        ),
    ]
